### ISSUE TITLE
Opção mostrando os meus picos

### ISSUE THREAD

**Issue by guuibayer** [ondetempico/pwa#13]

**Comment by JandersonConstantino** [comment]
Boa noite,
Quando tento cadastrar um pico para testar retorna um erro de acesso negado pra mim. :|

**Comment by guuibayer** [comment]
Boa noite Janderson,

Você poderia entrar no gitter do projeto pra trocarmos uma ideia? Já esbarrei também nesse problema, https://gitter.im/ondetempico/Lobby
